// import { ClerkProvider } from "@clerk/nextjs";
// import './globals.css'
// import type { Metadata } from "next";
// import { Inter,Outfit,Raleway} from 'next/font/google'
// import NavBar from "@/components/NavBar";

// const outfit =Raleway({ subsets: ['latin']})

// export const metadata: Metadata ={
//   title: 'Taxi_App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {

//   return (
//     <ClerkProvider>
//       <html lang="en" >
//         <body className={outfit.className}>
//           <NavBar/>

//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }




import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import NavBar from "@/components/NavBar";

const outfit = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Taxi_App",
  description: "Taxi Booking App By Debasish ",
  icons: {
    icon: "/taxi-icon.png", // Make sure this file is inside the public/ folder
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/taxi-icon.png" type="image/png" />
          <link rel="icon" href="/taxi-icon.ico" type="image/x-icon" />
          
        </head>

        <body className={outfit.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
